### ISSUE TITLE
the sly game series is setup the same way i was wondering if you found a way to decompress the data in the iso

### ISSUE THREAD

**Issue by theclub654** [maikelwever/rac-dvd-toc-parser#1]

**Comment by maikelwever** [comment]
This code is just a simple implementation of the description here: https://forum.xentax.com/viewtopic.php?t=12941

For rac 2, 3 and deadlocked, there is a parser/unpacker here: https://github.com/chaoticgd/wrench 

Maybe there's some information in that repo that might help you out.
